# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce1929525e2271c00f00e72b1b36bb69ae22d9ab326487ca8abc9d70c2f4bae528db4d7a35bb7328363070d20dc859a05a74e72b3a9b5ef55e53c32704343d21

test:
  secret_key_base: 9a3404fafff5ecf00a2dcfe71781dd71c7a22e89ff3a74a92bdfe76a08dbbfc031f6077b00da095c42df3a7b8da663f183c4115826c3447923c720bbfa1e8d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
